from pathlib import Path
import json,html
r=Path(__file__).resolve().parent
items=json.loads((r/'games.json').read_text())
def t(en,zh,tag='span',cls=''):
 return f'<{tag}'+(f' class="{cls}"' if cls else '')+f' data-en="{html.escape(en,quote=True)}" data-zh="{html.escape(zh,quote=True)}">{html.escape(en)}</{tag}>'
cards=[]
for i,g in enumerate(items):
 links=''
 if g['pkg']:links+=f'<a class="store" href="https://play.google.com/store/apps/details?id={g["pkg"]}" target="_blank" rel="noopener noreferrer">Google Play <span aria-hidden="true">↗</span></a>'
 if g.get('details'):links+='<a class="store" href="'+g['details']+'">'+t('Explore game','了解游戏')+' <span aria-hidden="true">↗</span></a>'
 if g.get('android_soon'):links+=t('Google Play coming soon','Google Play 即将上线','span','soon')
 if g['ios']: links+=t('iOS coming soon','iOS 即将上线','span','soon')
 if g['privacy']:links+='<a class="privacy" href="'+g['privacy']+'">'+t('Privacy','隐私政策')+'</a>'
 cards.append(f'''<article class="game" id="{g['id']}"><div class="game-art" style="--tint:{g['color']}"><span class="number">0{i+1}</span>{t(*g['category'],cls='category')}<img src="{g['id']}.png" alt="{html.escape(g['name'])} icon" width="144" height="144" loading="lazy"></div><div class="game-body"><h3>{html.escape(g['name'])}</h3>{t(g['category'][0],g['zh'],'p','subtitle')}{t(g['en'],g['cn'],'p','description')}{t(*g['tag'],'p','features')}<div class="game-links">{links}</div></div></article>''')
art=''.join(f'<a href="#{g["id"]}" class="tile tile-{i}" aria-label="{html.escape(g["name"])}"><img src="{g["id"]}.png" alt="" width="112" height="112"></a>' for i,g in enumerate(items[:6]))
page='''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Discover Jocelyn’s playful puzzle games: Mint, Color Dock, Lift Dock, Critter Zones, Cargo Loop, Don't Think Normal Color Sudoku Garden and Whistle Meadow."><meta name="theme-color" content="#f8f7f2"><meta property="og:title" content="Jocelyn Games — A little play, every day."><meta property="og:description" content="Small worlds. Clever puzzles. Find your next little escape."><meta property="og:image" content="https://seansheaton-oss.github.io/mint.png"><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="style.css"><title>Jocelyn Games — A little play, every day.</title><script src="site.js" defer></script></head><body>
'''
page+='<a class="skip" href="#games">Skip to games / 跳到游戏</a><header class="wrap"><a class="brand" href="./" aria-label="Jocelyn Games home"><span class="brand-mark" aria-hidden="true">j<span>•</span></span>jocelyn<span class="brand-small"> / games</span></a><nav aria-label="Main navigation"><a href="#games">'+t('Our games','我们的游戏')+'</a><a href="#contact">'+t('Get in touch','联系我们')+'</a><button id="language" type="button" aria-label="切换为中文">中文 <span aria-hidden="true">↗</span></button></nav></header>'
page+='<main class="wrap"><section class="hero" aria-labelledby="headline"><div class="hero-copy"><div class="eyebrow"><span class="dot"></span>'+t('SMALL GAMES. HAPPY MOMENTS.','小小的游戏，大大的快乐。')+'</div><h1 id="headline">'+t('A little play,','给日常，')+'<br>'+t('every day.','添一点好玩。','em')+'</h1>'+t('Small worlds. Clever puzzles. A collection of colorful games for your next well-earned break.','小小世界，藏着巧思。挑一款喜欢的游戏，在缤纷的谜题里，享受一段属于自己的轻松时光。','p','intro')+'<a class="primary" href="#games">'+t('Find your next game','发现你的下一款游戏')+' <span aria-hidden="true">↗</span></a><div class="hero-note">'+t('Made for curious minds & little escapes.','为好奇心，也为片刻闲暇。')+'</div></div><div class="hero-art"><div class="orbit"></div><span class="spark spark-one" aria-hidden="true">✳</span>'+art+'<span class="spark spark-two" aria-hidden="true">✦</span><span class="art-label">'+t('PICK A LITTLE ADVENTURE','选一场小小的冒险')+'</span></div></section>'
page+='<section id="games" aria-labelledby="games-title"><div class="section-heading"><div><div class="eyebrow">'+t('THE COLLECTION','游戏合集')+'</div><h2 id="games-title">'+t('Good things come in small games.','小小游戏，慢慢喜欢。')+'</h2></div><span class="count">'+str(len(items)).zfill(2)+' / '+t('GAMES','款游戏')+'</span></div><div class="games">'+''.join(cards)+'</div></section>'
page+='<section class="contact" id="contact"><div><div class="eyebrow">'+t('SAY HELLO','打个招呼')+'</div><h2>'+t('A thought, a question, a little hello?','有建议、有问题，或只是想打个招呼？')+'</h2>'+t('We’d love to hear from you. For game support, include the game name and your device.','欢迎来信。反馈游戏问题时，请附上游戏名称和设备型号，方便我们更快了解情况。','p')+'</div><a href="mailto:seansheaton@gmail.com">seansheaton@gmail.com <span aria-hidden="true">↗</span></a></section></main><footer class="wrap"><a class="brand" href="./">jocelyn<span class="brand-small"> / games</span></a><span>© 2026 Jocelyn</span><a href="/game-privacy-policies/">'+t('Privacy policies','隐私政策')+'</a></footer></body></html>'
(r/'index.html').write_text(page+'\n')
(r/'favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="18" fill="#cfea82"/><text x="23" y="45" font-family="Arial" font-weight="bold" font-size="44" fill="#24372b">j</text></svg>')
